import type { Booking, DemoReport } from '@/types'
import { formatLongDate } from '@/lib/date'
import { inr } from '@/lib/utils'
import { LAB_INFO } from '@/data/lab'

/**
 * Builds a standalone, self-contained HTML document for the demo receipt /
 * report so it can be downloaded and opened or printed in any browser.
 * No external assets are referenced — the branding is inline SVG + CSS.
 *
 * SECURITY: several of these values are free text — the patient name, the home
 * collection address (whose individual fields accept any character), package and
 * test names typed by an admin, and payment references. `openHtmlDocument` writes
 * the result into a same-origin document, so any value interpolated raw here is
 * stored XSS: a payload such as `<img src=x onerror=…>` typed into an address
 * field executes as soon as the receipt is opened — for lab staff too. Every
 * dynamic value below therefore goes through `esc()`. The LAB_INFO values are
 * compile-time constants from src/data/lab.ts and carry no user input.
 */

/** Escapes a value for safe interpolation into HTML text or a quoted attribute. */
export function escapeHtml(value: unknown): string {
  return String(value ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

/** Short alias for use inside the document templates below. */
const esc = escapeHtml

const sharedHead = (title: string) => `
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<style>
  *{box-sizing:border-box}
  body{margin:0;padding:28px;background:#f4f7fb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;color:#0a2540}
  .sheet{max-width:760px;margin:0 auto;background:#fff;border-radius:16px;overflow:hidden;box-shadow:0 8px 32px rgba(10,37,64,.10)}
  .bar{background:linear-gradient(100deg,#0a2540 0%,#1f436f 55%,#136e6b 100%);padding:22px 26px;color:#fff}
  .bar h1{margin:0;font-size:19px;letter-spacing:-.2px}
  .bar p{margin:4px 0 0;font-size:12.5px;color:rgba(255,255,255,.78)}
  .body{padding:26px}
  .demo-flag{background:#fffaeb;border:1px solid #fde68a;color:#b45309;border-radius:10px;padding:10px 12px;font-size:12px;line-height:1.5;margin-bottom:20px;font-weight:600}
  .grid{display:flex;flex-wrap:wrap;gap:18px 28px;margin-bottom:22px}
  .grid>div{min-width:150px}
  .k{font-size:10.5px;text-transform:uppercase;letter-spacing:.1em;color:#64748b;font-weight:700;margin-bottom:3px}
  .v{font-size:13.5px;font-weight:600}
  table{width:100%;border-collapse:collapse;margin:6px 0 18px}
  th{text-align:left;font-size:10.5px;text-transform:uppercase;letter-spacing:.08em;color:#64748b;padding:9px 10px;background:#f8fafc;border-bottom:1px solid #e2e8f0}
  td{padding:10px;font-size:13px;border-bottom:1px solid #eef2f7}
  .right{text-align:right}
  .total{font-size:16px;font-weight:700}
  h2{font-size:13.5px;text-transform:uppercase;letter-spacing:.08em;color:#0a2540;margin:24px 0 10px}
  .foot{border-top:1px solid #eef2f7;padding:18px 26px;font-size:11.5px;color:#64748b;line-height:1.6}
  .badge{display:inline-block;padding:3px 9px;border-radius:999px;font-size:11px;font-weight:700;background:#effaf3;color:#0f6a36}
  .badge.pending{background:#fffaeb;color:#b45309}
  .flag-normal{color:#0f6a36;font-weight:600}
  .flag-borderline{color:#b45309;font-weight:600}
  .flag-review{color:#b91c1c;font-weight:600}
  @media print{body{background:#fff;padding:0}.sheet{box-shadow:none;border-radius:0}.demo-flag{border:1px solid #b45309}}
</style>
`

const header = (subtitle: string) => `
<div class="bar">
  <h1>LabCare Diagnostics</h1>
  <p>${esc(subtitle)}</p>
  <p>${LAB_INFO.addressLine1}, ${LAB_INFO.addressLine2} · ${LAB_INFO.phone} · ${LAB_INFO.email} · DEMO CONTACT DETAILS</p>
</div>
`

const footer = (note: string) => `
<div class="foot">
  <strong style="color:#0a2540">Demonstration document.</strong> ${esc(note)}<br />
  This file was generated by the LabCare Diagnostics demo application. All names, amounts, packages, test results and
  contact details are fictional sample data. ${LAB_INFO.licenseNote}
</div>
`

export function buildReceiptHtml(booking: Booking): string {
  const rows = [
    ['Package', booking.packageName],
    ['Number of tests', `${booking.testsCount} tests included`],
    ['Collection method', booking.collectionMethod],
    ['Appointment', `${formatLongDate(booking.appointmentDate)} · ${booking.timeSlot}`],
    ['Payment method', booking.payment.method],
    ['Payment status', booking.payment.state],
  ]

  const address = esc(
    booking.address
      ? `${booking.address.line1}, ${booking.address.area}, ${booking.address.city} – ${booking.address.pincode}${
          booking.address.landmark ? ` (${booking.address.landmark})` : ''
        }`
      : 'Sample collection at LabCare Diagnostics, Rajapalayam',
  )

  return `<!doctype html>
<html lang="en"><head>${sharedHead(`Booking receipt ${booking.bookingNo}`)}</head>
<body>
<div class="sheet">
  ${header('Booking Receipt · Demo Document')}
  <div class="body">
    <div class="demo-flag">DEMO RECEIPT — NOT A REAL PAYMENT RECEIPT. No money has been collected and no real payment gateway was used.</div>

    <div class="grid">
      <div><div class="k">Booking ID</div><div class="v">${esc(booking.bookingNo)}</div></div>
      <div><div class="k">Booking date</div><div class="v">${esc(formatLongDate(booking.createdAt.slice(0, 10)))}</div></div>
      <div><div class="k">Status</div><div class="v"><span class="badge ${booking.status === 'Pending' ? 'pending' : ''}">${esc(booking.status)}</span></div></div>
      <div><div class="k">Expected report</div><div class="v">${esc(booking.reportAvailability)}</div></div>
    </div>

    <h2>Patient details</h2>
    <div class="grid">
      <div><div class="k">Patient name</div><div class="v">${esc(booking.patient.fullName)}</div></div>
      <div><div class="k">Age / Gender</div><div class="v">${esc(booking.patient.age)} yrs · ${esc(booking.patient.gender)}</div></div>
      <div><div class="k">Mobile</div><div class="v">${esc(booking.patient.mobile)}</div></div>
      <div><div class="k">Email</div><div class="v">${esc(booking.patient.email)}</div></div>
    </div>

    <h2>Appointment &amp; collection</h2>
    <table>
      ${rows.map(([k, v]) => `<tr><td style="width:38%;color:#475569">${esc(k)}</td><td style="font-weight:600">${esc(v)}</td></tr>`).join('')}
      <tr><td style="color:#475569">Collection address</td><td>${address}</td></tr>
    </table>

    <h2>Charges</h2>
    <table>
      <tr><td>Package MRP</td><td class="right" style="color:#94a3b8;text-decoration:line-through">${inr(booking.pricing.mrp)}</td></tr>
      <tr><td>Package discount</td><td class="right" style="color:#0f6a36">− ${inr(booking.pricing.discount)}</td></tr>
      <tr><td>Package price</td><td class="right" style="font-weight:600">${inr(booking.pricing.packagePrice)}</td></tr>
      <tr><td>Home sample collection fee</td><td class="right">${booking.pricing.homeCollectionFee ? inr(booking.pricing.homeCollectionFee) : 'Waived'}</td></tr>
      <tr><td class="total">Total payable</td><td class="right total">${inr(booking.pricing.total)}</td></tr>
      <tr><td>Amount paid${booking.payment.state === 'Pay at Lab' ? ' (payable at lab)' : ''}</td><td class="right">${
        booking.payment.state === 'Pay at Lab' ? inr(0) : inr(booking.payment.amountPaid)
      }</td></tr>
    </table>
    ${
      booking.payment.reference
        ? `<p style="font-size:12px;color:#64748b">Demo payment reference: <strong>${esc(booking.payment.reference)}</strong> (simulated)</p>`
        : `<p style="font-size:12px;color:#64748b">Payment selected: <strong>${esc(booking.payment.method)}</strong> — collect at the laboratory.</p>`
    }

    <h2>Preparation reminder</h2>
    <p style="font-size:12.5px;line-height:1.65;color:#475569;margin:0">
      Follow the preparation instructions shown on your booking page and shared by the laboratory. This document is not
      medical advice. Please contact the lab on ${LAB_INFO.phone} if your appointment needs to change.
    </p>
  </div>
  ${footer('This receipt is provided only to demonstrate the booking confirmation experience.')}
</div>
</body></html>`
}

const flagClass = (flag: string) =>
  flag === 'Normal' ? 'flag-normal' : flag === 'Borderline' ? 'flag-borderline' : 'flag-review'

export function buildReportHtml(report: DemoReport): string {
  return `<!doctype html>
<html lang="en"><head>${sharedHead(`Demo report ${report.bookingNo}`)}</head>
<body>
<div class="sheet">
  ${header('Sample Diagnostic Report · Demo Document')}
  <div class="body">
    <div class="demo-flag">DEMO REPORT — NOT A REAL MEDICAL REPORT. Sample values only. This is not a diagnosis and must not be used for any health decision.</div>

    <div class="grid">
      <div><div class="k">Patient name</div><div class="v">${esc(report.patientName)}</div></div>
      <div><div class="k">Age / Gender</div><div class="v">${esc(report.age)} yrs · ${esc(report.gender)}</div></div>
      <div><div class="k">Booking ID</div><div class="v">${esc(report.bookingNo)}</div></div>
      <div><div class="k">Package</div><div class="v">${esc(report.packageName)}</div></div>
      <div><div class="k">Sample collected</div><div class="v">${esc(report.collectedOn)} · 08:35 AM</div></div>
      <div><div class="k">Report released</div><div class="v">${esc(report.reportedOn)} · 05:40 PM</div></div>
    </div>

    <h2>Results (sample demonstration values)</h2>
    <table>
      <thead><tr><th>Test</th><th class="right">Result</th><th>Unit</th><th>Reference range</th><th>Flag</th></tr></thead>
      <tbody>
        ${report.rows
          .map(
            (r) => `<tr>
              <td style="font-weight:600">${esc(r.test)}</td>
              <td class="right">${esc(r.value)}</td>
              <td>${esc(r.unit)}</td>
              <td>${esc(r.referenceRange)}</td>
              <td class="${flagClass(r.flag)}">${esc(r.flag)}</td>
            </tr>`,
          )
          .join('')}
      </tbody>
    </table>

    <h2>Laboratory remarks</h2>
    <p style="font-size:12.5px;line-height:1.65;color:#475569;margin:0">${esc(report.remarks)}</p>

    <p style="font-size:12px;color:#64748b;margin-top:20px">
      Released by: <strong>Demo Pathologist (fictional)</strong> · Demo registration ${LAB_INFO.licenseNote}
    </p>
  </div>
  ${footer('Reference ranges and values are illustrative placeholders created to demonstrate the report delivery flow.')}
</div>
</body></html>`
}

export function openHtmlDocument(html: string) {
  const w = window.open('', '_blank')
  if (!w) return false
  w.document.write(html)
  w.document.close()
  return true
}
